部署到杭州办公测试环境:
  script:
    - npm install --registry=http://npm.hekr.me
    - npm run docs
    - rm -rf /home/diao.cheng/fed-docs/auto/*
    - cp -R docs/* /home/diao.cheng/fed-docs/auto/
  tags:
    - hz-test
  only:
    - master
  when: always
  environment:
    name: 10.10.1.3
    url: http://10.10.1.3:7777/auto/index.html
